### ISSUE TITLE
Electron

### ISSUE THREAD

**Issue by di48l069** [CodeDotJS/facebook-dl#1]
Hi there can you implement this in electron app?

**Comment by CodeDotJS** [comment]
@di48l069 I can, but I haven't finished the writing the core of this tool.

Since, my 12th board exams are going on, so, I'll start writing the code after 24th or March.

**Comment by di48l069** [comment]
Epic

> On Mar 5 2016, at 12:48 am, Rishi Giri &lt;notifications@github.com&gt;
wrote:  

>

> [@di48l069](https://github.com/di48l069) I can, but I haven't finished the
writing the core of this tool.

>

> Since, my 12th board exams are going on, so, I'll start writing the code
after 24th or March.

>

> —  
Reply to this email directly or [view it on
GitHub](https://github.com/CodeDotJS/facebook-dl/issues/1#issuecomment-1925069
54).![](https://github.com/notifications/beacon/AHbwWZ7R7r1GHOmkmxzNSUJGmPQF-
92iks5pqLbZgaJpZM4HmhL_.gif)
